name: webrtc
description: Frontend app for WebRTC
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  get_it: ^8.2.0
  logger: ^2.6.1
  dafluta: ^5.5.1
  flutter_webrtc: ^1.1.0
  json_annotation: ^4.9.0

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_crashlytics: ^5.0.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.7.0
  flutter_lints: ^6.0.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
