name: pong
description: Frontend app for Pong
publish_to: none
version: 0.0.1+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter_webrtc: ^1.1.0

  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_crashlytics: ^5.0.0

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
